name: test
on: [push]
jobs:
  unittests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: current_branch

      - name: Build Docker
        run: docker build -t simula/builconf -f Dockerfile . --build-arg PKG_BRANCH=${{ steps.current_branch.outputs.branch }}

