name: test
on:
  push:
  pull_request:
  schedule:
    - '0 3 * * 7' # every sunday at 3
jobs:
  docker_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Branch name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: current_branch

      - name: Build Docker
        run: docker build -t simula/buildconf -f Dockerfile . --build-arg PKG_BRANCH=${{ steps.current_branch.outputs.branch }}

